steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/extract', '.']
      dir: 'extract'

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/extract']

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - 'run'
          - 'deploy'
          - 'extract'
          - '--image=gcr.io/$PROJECT_ID/extract'
          - '--region=us-central1'
          - '--platform=managed'
          - '--allow-unauthenticated'
      entrypoint: 'gcloud'

images:
    - 'gcr.io/$PROJECT_ID/extract'