steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/extract-service', '.']
      dir: 'extract-service'

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/extract-service']

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - 'run'
          - 'deploy'
          - 'extract-service'
          - '--image=gcr.io/$PROJECT_ID/extract-service'
          - '--region=us-central1'
          - '--platform=managed'
          - '--allow-unauthenticated'
      entrypoint: 'gcloud'

images:
    - 'gcr.io/$PROJECT_ID/extract-service'